version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=hireflix
      - DB_USERNAME=root
      - DB_PASSWORD=password

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hireflix
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
